// <auto-generated />
namespace DiplomaUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class GenDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202305011459078_GenDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
